name: Blue/Green deployment workflow
on: [push]
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  deploy_test_stack:
    environment: 
      name: test
      url: ${{ steps.set_outputs.outputs.TEST_URL }}
    runs-on: ubuntu-latest
    outputs:
      TEST_URL: ${{ steps.set_outputs.outputs.TEST_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: 'arn:aws:iam::815510839581:role/github-actions-deployment-role'
          aws-region: 'eu-central-1'

      - name: Check credentials
        run: aws sts get-caller-identity

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ./cdk/

      - name: Synth stack
        run: cd cdk && yarn cdk synth

      - id: deploy-stack
        name: Deploy stack
        run: cd cdk && TEST_REGION=eu-central-1 TEST_ACCOUNT=815510839581 yarn cdk deploy HelloConstructsStack-test --outputs-file ./cdk-outputs.json --require-approval never
  
      - name: Edit json
        id: set_outputs
        run:  |
          values=$(jq -r ".[] | values[]" cdk/cdk-outputs.json)
          echo "TEST_URL<<EOF" >> "${GITHUB_OUTPUT}"
          echo "$values" >> "${GITHUB_OUTPUT}"
          echo "EOF" >> "${GITHUB_OUTPUT}"

  deploy_prod_stack:
    environment:
      name: production
      url: ${{ steps.set_outputs.outputs.PROD_URL }}
    needs: deploy_test_stack
    runs-on: ubuntu-latest    
    outputs:
      PROD_URL: ${{ steps.set_outputs.outputs.PROD_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: 'arn:aws:iam::580240676696:role/GitHubActionsDeploymentRole'
          aws-region: 'eu-central-1'

      - name: Check credentials
        run: aws sts get-caller-identity

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ./cdk/

      - name: Synth stack
        run: cd cdk && yarn cdk synth

      - id: deploy-stack
        name: Deploy stack
        run: cd cdk && BLUE_REGION=eu-central-1 BLUE_ACCOUNT=580240676696 yarn cdk deploy HelloConstructsStack-blue --require-approval never
      
      - name: Edit json
        id: set_outputs
        run:  |
          values=$(jq -r ".[] | values[]" cdk/cdk-outputs.json)
          echo "PROD_URL<<EOF" >> "${GITHUB_OUTPUT}"
          echo "$values" >> "${GITHUB_OUTPUT}"
          echo "EOF" >> "${GITHUB_OUTPUT}"